# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
