# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='JohnnyWalkerBlue', max_length=255),
            preserve_default=False,
        ),
    ]
