# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='book_authors.Books'),
        ),
    ]
